server:
  port: 8084

spring:
  application:
    name: catalog-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    cl.duoc.catalog: INFO
