server:
  port: 8080

spring:
  application:
    name: ms-pedidos360-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/47c2bee0-5950-430f-9276-bfc083e3d1da/v2.0

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  security:
    enabled: false

logging:
  level:
    org.springframework.security: TRACE
