server:
  port: 8085

spring:
  application:
    name: report-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    cl.duoc.report: INFO
